/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author namBH
 */
public class MainApplet extends javax.swing.JApplet {

    /**
     * Initializes the applet MainApplet
     */
    @Override
    public void init() {
        this.setSize(1024, 600);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    loadForm();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void loadForm(){
        mniPlayQuiz.setEnabled(false);
        mniChangePassword.setEnabled(false);
        mniViewResult.setEnabled(false);
        mniLogin.setBorder(BorderFactory.createEtchedBorder());
        
        loadLoginPanel();
    }
    
    private void loadLoginPanel(){
        LoginPanel pnlLogin = new LoginPanel(pnlMain, mniLogin, mniRegister, mniPlayQuiz, mniChangePassword, 
                mniViewResult, mniAdmin, lblStatus);
        loadMainPanel(pnlLogin);
    }
    
    private void loadMainPanel(JPanel pnl){
        pnlMain.removeAll();
        pnlMain.setLayout(new BorderLayout());
        pnlMain.add(pnl);
        pnlMain.revalidate();
    }
    
    private void setEmptyBorderMenuItem() {
        mniLogin.setBorder(BorderFactory.createEmptyBorder());
        mniRegister.setBorder(BorderFactory.createEmptyBorder());
        mniPlayQuiz.setBorder(BorderFactory.createEmptyBorder());
        mniChangePassword.setBorder(BorderFactory.createEmptyBorder());
        mniViewResult.setBorder(BorderFactory.createEmptyBorder());
        mniAdmin.setBorder(BorderFactory.createEmptyBorder());
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMni = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        mniLogin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        mniRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mniPlayQuiz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mniChangePassword = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mniViewResult = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mniAdmin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        pnlMni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMni.setMinimumSize(new java.awt.Dimension(100, 50));
        pnlMni.setPreferredSize(new java.awt.Dimension(730, 60));
        pnlMni.setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 30));

        mniLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1387320409_log-in.png"))); // NOI18N
        mniLogin.setText("         Login       ");
        mniLogin.setFocusable(false);
        mniLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(mniLogin);

        jLabel9.setText("|");
        jToolBar1.add(jLabel9);

        mniRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        mniRegister.setText("       Register      ");
        mniRegister.setFocusable(false);
        mniRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mniRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegisterActionPerformed(evt);
            }
        });
        jToolBar1.add(mniRegister);

        jLabel5.setText("|");
        jToolBar1.add(jLabel5);

        mniPlayQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yes.png"))); // NOI18N
        mniPlayQuiz.setText("       Play Quiz     ");
        mniPlayQuiz.setFocusable(false);
        mniPlayQuiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniPlayQuiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mniPlayQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPlayQuizActionPerformed(evt);
            }
        });
        jToolBar1.add(mniPlayQuiz);

        jLabel1.setText("|");
        jToolBar1.add(jLabel1);

        mniChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changePass2.png"))); // NOI18N
        mniChangePassword.setText(" Change Password ");
        mniChangePassword.setFocusable(false);
        mniChangePassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniChangePassword.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mniChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePasswordActionPerformed(evt);
            }
        });
        jToolBar1.add(mniChangePassword);

        jLabel2.setText("|");
        jToolBar1.add(jLabel2);

        mniViewResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewresult.png"))); // NOI18N
        mniViewResult.setText("     View Result    ");
        mniViewResult.setFocusable(false);
        mniViewResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniViewResult.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mniViewResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewResultActionPerformed(evt);
            }
        });
        jToolBar1.add(mniViewResult);

        jLabel4.setText("|");
        jToolBar1.add(jLabel4);

        mniAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings_file.png"))); // NOI18N
        mniAdmin.setText("       Admin     ");
        mniAdmin.setFocusable(false);
        mniAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mniAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mniAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(mniAdmin);

        pnlMni.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMni, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 30));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblStatus.setText("Status");
        jPanel2.add(lblStatus, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pnlMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void mniRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegisterActionPerformed
        RegisterPanel pnlRegister = new RegisterPanel();
        loadMainPanel(pnlRegister);
        setEmptyBorderMenuItem();
        mniRegister.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_mniRegisterActionPerformed

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        loadLoginPanel();
        setEmptyBorderMenuItem();
        mniLogin.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniPlayQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPlayQuizActionPerformed
        PlayQuizPanel pnl = new PlayQuizPanel(lblStatus);
        loadMainPanel(pnl);

        mniPlayQuiz.setEnabled(true);
        mniChangePassword.setEnabled(true);
        mniViewResult.setEnabled(true);
        setEmptyBorderMenuItem();
        mniPlayQuiz.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_mniPlayQuizActionPerformed

    private void mniChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePasswordActionPerformed
        ChangePassPanel pnl = new ChangePassPanel(lblStatus);
        loadMainPanel(pnl);
        
        setEmptyBorderMenuItem();
        mniChangePassword.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_mniChangePasswordActionPerformed

    private void mniViewResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewResultActionPerformed
        ViewResultPanel pnl = new ViewResultPanel(lblStatus);
        loadMainPanel(pnl);
        
        setEmptyBorderMenuItem();
        mniViewResult.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_mniViewResultActionPerformed

    private void mniAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdminActionPerformed
        AdminLoginPanel pnl = new AdminLoginPanel(pnlMain, mniLogin, mniRegister, mniPlayQuiz, 
                mniChangePassword, mniViewResult, mniAdmin, lblStatus);
        loadMainPanel(pnl);
        setEmptyBorderMenuItem();
        mniAdmin.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_mniAdminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JButton mniAdmin;
    private javax.swing.JButton mniChangePassword;
    private javax.swing.JButton mniLogin;
    private javax.swing.JButton mniPlayQuiz;
    private javax.swing.JButton mniRegister;
    private javax.swing.JButton mniViewResult;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMni;
    // End of variables declaration//GEN-END:variables
}
